version: '3'

tasks:
  lint:
    desc: Lint the code
    cmds:
      - ruff check sec_ai/ --fix
      - mypy sec_ai/

  test:
    desc: Run tests and check code coverage
    cmds:
      - coverage run -m pytest tests/
      - coverage report --fail-under=100 --skip-covered

  prepare: 
    desc: Lint the code and run all checks
    deps: [lint, test]
